---
title: "graphstatsr"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{graphstatsr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Easy stats module

This module allows users to carry out descriptive analyses like Principal Component Analysis (PCA) and boxplots associated with statistical tests.

Here is a video demonstrating how to use this module:

<div style="text-align: center;">
  <iframe width="756" height="415" src="https://www.youtube.com/embed/yRG_FF2K6Xs?si=C1WnXKmeGwfV96va" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>

- Input Data: Users can drag and drops quantification file and metadata file in the corresponding fields. Filters and tranformations can be applied on dataset. Merge datasets button makes the dataset ready for further analysis.

The features table must include the mandatory column names: **features**, **type**, and **unit**. All other columns correspond to sample names, which can be defined by the user.

The metadata table must include the mandatory column name: **sample.id**. Additional columns represent sample factors or characteristics.

The information in the **sample.id** column of the metadata table must match the sample names present in the features table.


- Principal Component Analysis (PCA): In this submodule, the dataset is preprocessed to handle missing values. User can choose which component to display. [Learn more about PCA](https://sites.google.com/site/mb3gustame/indirect-gradient-analysis/principal-components-analysis?authuser=0)

- Boxplots: Boxplots are displayed based on the factor selected by the user. Multiple factors can be chosen, forming combinations of their levels. Non-parametric tests are performed using pairwise Wilcoxon tests, with p-values adjusted using the FDR correction.


# Isoplot module

This module allows users to generate stacked bar plots with isotopic data. It takes as input the output table from [Isocor](https://github.com/MetaSys-LISBP/IsoCor).


<div style="text-align: center;">
  <iframe width="756" height="415" src="https://www.youtube.com/embed/_VyaIAx-8GY?si=dr0Erpa6gUHuNtOG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>


## MSPT submodule

MSPT is a submodule of IsoPlot, able to analysis "pascal triangle" sample to validate experiment. (ref. Millard, Pierre, et al. 2014. “Isotopic Studies of Metabolic Systems by Mass Spectrometry: Using Pascal’s Triangle To Produce Biological Standards with Fully Controlled Labeling Patterns.” Analytical Chemistry 86 (20): 10288–95. https://doi.org/10.1021/ac502490g;  https://github.com/llegregam/PascalTriangle)

<div style="text-align: center;">
  <iframe width="756" height="415" src="https://www.youtube.com/embed/bCcZvafnRPg?si=iCDQ-DIPHEI4Wi-F" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
